name: samap-gut

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.12
  - pip
  - blast
  - hnswlib>=0.8
  - leidenalg>=0.10
  - python-igraph
  - snakemake-minimal
  - jupyterlab
  - ipykernel
  - pip:
      - sc-samap==3.0.1
